### ISSUE TITLE
noMultilineStringRule test failure on master

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Microsoft/tslint-microsoft-contrib#134]
OS: Windows 10 v10586
Node: v6.1.0
Built-in cmd

![image](https://cloud.githubusercontent.com/assets/3335181/15306293/204a8bd8-1b7e-11e6-8dd2-8e92e56ba656.png)

**Comment by HamletDRC** [comment]
Hi @JoshuaKGoldberg 
This is failing because you have the wrong line endings configured in Git. 

The main page of the project has instructions to clone the repo like this: 

    git config --global core.autocrlf input
    git config --global core.eol lf
    git clone git@github.com:Microsoft/tslint-microsoft-contrib.git

Once the repo is cloned, then I think you can revert the global config changes and just make these changes local to the project.

**Comment by JoshuaKGoldberg** [comment]
Ah :) user error. My apologies.
