### ISSUE TITLE
Possible false positive for 'no-reserved-keywords'

### ISSUE THREAD

**Issue by Hufschmidt** [Microsoft/tslint-microsoft-contrib#166]
The following raises a no-reserved-keywords warning:

    interface RestInterface {
      'class': String;
    }

While `class` is definitly a reserved key-word and warning for

    interface RestInterface {
      class: String;
    }

seems like a very good idea (without quotes), the first should no be warned about, since for example

    class Foo {
      private 'bar'() { }
    }

gets transformed into

    var Foo = (function () {
      function Foo() {
      }
      Foo.prototype['bar'] = function () {
      };
      return Foo;
    })();

**Potential Use-Case:** Create interface for external (REST) api you don't have control over.

**Comment by HamletDRC** [comment]
I see the point. On MSE we have a generated d.ts file from a REST API and we have the same issue. We just add a suppress warnings on that particular file. 

If I understand correctly, you propose that the rule ignore any property names that are enclosed in quotes (single or double presumably). As an alternative, you can always add the suppress warning command around that prop. It is a little more verbose but a little clearer as well. 

I think Microsoft recommends this rule because reserved keywords can cause confusion. I don't think there is anything inherently unsafe about it though.

**Comment by Hufschmidt** [comment]
> I see the point. On MSE we have a generated d.ts file from a REST API and we have the same issue. We just add a suppress warnings on that particular file.

You are absolutely right, this is definitly the most save solution, the only downside is that I _personally_ try to avoid linter-comments in my source-code. (or is there another way?)

My prefered solution would be an opt-in setting for `no-reserved-keywords` eg.

    "no-reserved-keywords": [
      true,
      "allow-quoted"
    ]

But this is just personal preference.

**Comment by HamletDRC** [comment]
done. thanks for the report. 

I named the parameter "allow-quoted-properties" because it only applies to unterface properties and not field declarations.
