### ISSUE TITLE
`import-name` is hard to enforce for node modules

### ISSUE THREAD

**Issue by jeffijoe** [Microsoft/tslint-microsoft-contrib#172]
E.g. `is-plain-object`, `app-module-path` - many npm packages have these names that are invalid in TS/JS.

```
import isPlainObject from 'is-plain-object'
```

Is it possible to ignore files resolved to node_modules?

**Comment by HamletDRC** [comment]
Hi @jeffijoe  , thanks for bring this up! I am tagging this "feature-request". 

Would an acceptable solution be to convert dashes to camel case, so that "is-plain-object" must be aliased as isPlainObject or IsPlainObject? If yes, should it be with, without, or insensitive to the casing of the first letter? 

import-name is actually a very important rule for our project because it enables us to run and execute large code transformations across the project because we are guaranteed that all the imported names are consistent. Because this consistency is so valuable, I would recommend "IsPlainObject" because it forces a choice on the case of the first letter and it is also more common to import a module than a single function.

**Comment by jeffijoe** [comment]
@HamletDRC That sounds reasonable - I'd say the first letter should be case insensitive - in Node it is not uncommon to import just a single function.

```js
const map = require(lodash/map')
const yenv = require('yenv')
const env = yenv();
```

These happen quite a lot. So `isPlainObject` or `IsPlainObject` should both validate.

**Comment by HamletDRC** [comment]
@jeffijoe this has overlap with #137 . I am going to fix that issue and then see if the solution works for you here.

**Comment by HamletDRC** [comment]
@jeffijoe I closed this issue with this commit: https://github.com/Microsoft/tslint-microsoft-contrib/commit/a7c698680bcba584b64303655e10e9c6aa67262b

Please see the unit test because it contains your example of 'is-plain-object'. 

Is this an acceptable resolution for you? It allows you to convert 'is-plain-object' to isPlainObject, but it is not the dashs-to-camel-case logic that we discussed here. My assumption is that this general solution is a little more verbose for you but you don't have too many exceptions so it is not too much of a burden. 

If you really want the dashs-to-camel-case logic instead then please just reopen this issue and I can implement it. Otherwise, this is closed and I'll make a release soon.

**Comment by jeffijoe** [comment]
This is usually only a problem for node_modules - all npm packages must be kebab-cased so maybe just exclude them from the rule?

**Comment by HamletDRC** [comment]
Reopening this so that we can better handle kebab cased imports.
