### ISSUE TITLE
Error: Unsupported TypeScript version: 2.0.0

### ISSUE THREAD

**Issue by evusik** [Microsoft/tslint-microsoft-contrib#182]
[tslint.txt](https://github.com/Microsoft/tslint-microsoft-contrib/files/381801/tslint.txt)

Hi,

I'm getting the `Error: Unsupported TypeScript version: 2.0.0` using 
`typescript@2.0.0 node_modules\typescript`
`tslint@3.13.0 node_modules\tslint`

Should TS 2.0 be supported in tslint 3.13.0? If yes, do you have any pointers what might be wrong?

The command I execute is
`tslint --format json --config ./tslint.json --out TsLint_out.json './checkout/**/*.ts'`

I asked the same question in https://github.com/palantir/tslint/issues/1428 and got pointed to the custom rules implementation, which come from tslint-microsoft-contrib. The rule set tslint.json is attached (with txt extension).

Thanks

**Comment by HamletDRC** [comment]
Hi @evusik. Thanks for taking the time to file an issue. 

We added TypeScript 2.0 support in the last release (2.0.9) as #91. 
I am going to close this issue since I believe it is a duplicate. 

If it is still happening to you after upgrading to 2.0.9 then please leave a comment below and I can look into it again. 

Thanks.

**Comment by evusik** [comment]
HI @HamletDRC,

thanks a lot for the info - I checked that we're using `tslint-microsoft-contrib@2.0.8`

However, we get this by doing
`npm install tslint-microsoft-contrib`

I will ping you in private Re: how to get 2.0.9 to our npm.

Thanks!
