### ISSUE TITLE
Create a rule generator by using a micro-generator f/w

### ISSUE THREAD

**Issue by loicraux** [Microsoft/tslint-microsoft-contrib#258]
Using a micro-generator framework such as [plop](https://github.com/amwmedia/plop) would make it easy for all contributors of this repository to create new rules with a level of uniformity, and also faster, by asking a set a questions and boilerplating the appropriate code.

Also because [context switching is expensive](http://www.petrikainulainen.net/software-development/processes/the-cost-of-context-switching/) :) and [saving time is not the only benefit to automating workflows](https://medium.com/@kentcdodds/an-argument-for-automation-fce8394c14e2)

What are your thoughts about this ? Also considering time versus ROI (https://xkcd.com/1205/) ?

**Comment by danielmanesku** [comment]
Hamlet would know more if this is needed in this project, as there is already some generator available. I just wanted to say that idea of plop is very good!

**Comment by HamletDRC** [comment]
I tried this a few weeks ago, but the command line node app was broken for Windows. It was something other than plop and Inquirer.js though. It looks like Inquirer.js does work in Windows and git-bash. 

This is a good idea. I would just add Inquirer.js to the build and not use plop because we don't really need an entire templating engine when what we have already works. But if someone submits a PR that rewrites everything in Plop then that is OK too.
