### ISSUE TITLE
[enhancement] publish rules to nuget.org

### ISSUE THREAD

**Issue by bgold09** [microsoft/tslint-microsoft-contrib#346]
For projects that leverage NuGet packages instead of npm, publishing these rules to [nuget.org](nuget.org) would be a big help. This is often the case for many Microsoft projects.

**Comment by HamletDRC** [comment]
cc @JoshuaKGoldberg since you had the same request. 

@bgold09 I have no idea how to do this. Joshua and I discussed this last year, but I don't user Nuget so I didn't push it forward. 

How many hours would it take you to add Nuget support? Can you roughly list the tasks required in the description?

**Comment by JoshuaKGoldberg** [comment]
There are two components to adding NuGet support:

1. Create tool that generates a NuGet package containing just tslint-microsoft-contrib
2. Publish the generated packages to NuGet, either automatically or manually

1 is extremely simple. See https://github.com/joshuakgoldberg/tslint-nuget. 
2 is easy to do manually (though I've been woefully lazy at keeping up to date since my team switch to npm). I haven't seen examples of it getting done automatically, though in theory it should be possible if you have either a Windows CI environment or Mono on a Linux one.

**Comment by bgold09** [comment]
We should be able to accomplish this by [integrating with Appveyor to publish to a NuGet feed](https://www.appveyor.com/docs/deployment/nuget/). My suggestion is to leverage the [git-flow](http://nvie.com/posts/a-successful-git-branching-model/) model and Appveyor's [per-branch configuration functionality](https://www.appveyor.com/docs/branches/#conditional-build-configuration) and publish to nuget.org only from release branches. 

Optionally we could also publish to a [http://docs.myget.org/docs/walkthrough/getting-started-with-nuget](MyGet) feed on every build for testing purposes.

**Comment by bgold09** [comment]
@HamletDRC what does your typical release process look like for this package?

**Comment by bgold09** [comment]
Ah never mind, found the wiki page on releases: https://github.com/Microsoft/tslint-microsoft-contrib/wiki/Releases

**Comment by bgold09** [comment]
@HamletDRC could you [create a new AppVeyor project for this repo](https://ci.appveyor.com/projects/new)? From there I should be able to make the changes I need by making a config file for the builds.

**Comment by JoshuaKGoldberg** [comment]
Just coming back to this - we now have TravisCI builds running on Windows _(whoohoo!)_ so I can take a stab at also publishing to NuGet.

We haven't forgotten about this 😃.

**Comment by JoshuaKGoldberg** [comment]
### 💀 _**It's time!**_ 💀

**TSLint is being deprecated**; therefore, it and tslint-microsoft-contrib are no longer accepting pull requests for major new changes or features. See https://github.com/palantir/tslint/issues/4534. 😱

If you'd like to see this change implemented, you have two choices:
* **Recommended:** Check if this is available in [ESLint](https://eslint.org) + [typescript-eslint](https://typescript-eslint.io) ✅
* _Not Recommended: Fork TSLint or tslint-microsoft-contrib locally_ 🤷‍♂️

👋 It was a pleasure open sourcing with you!

_If you believe this message was posted here in error, please comment so we can re-open the issue!_
