### ISSUE TITLE
4.0.1 contained breaking changes but was published as patch

### ISSUE THREAD

**Issue by SimonSchick** [Microsoft/tslint-microsoft-contrib#352]
A lot of our TS projects are now failing due to these *breaking* changes.
Would it be possible to release updates like these as `major` in the future?

**Comment by HamletDRC** [comment]
I am not aware of any breaking change. What is the issue?

**Comment by HamletDRC** [comment]
Given the release notes, I don't know what could have been a breaking change: https://github.com/Microsoft/tslint-microsoft-contrib/wiki/Release-Notes

Was it that you were still using no-unused-variable from our project?

**Comment by SimonSchick** [comment]
Sorry for being unclear here.

The breaking change was that the default ruleset you provide via 

```"extends": "tslint-microsoft-contrib",```

changed, thus causing previously working builds to fail.

**Comment by HamletDRC** [comment]
It sounds like you are proposing that we increase the major version of the library every time we add a new rule. I don't think this is what we want.

If we remove a rule then we will increase the version number, because removing a rule would break tslint and cause it to error and not even run. 
If we modify a rule (i.e. fix a bug) to find more violations then we will *not* increase the version number because tslint will continue to run and function but your personal build might fail with some new tslint violations. 
If we add a new rule then we will *not* increase the version number for the same reason that fixing a bug would not increase the number. 

I would say there is a difference between a change that will cause tslint to fail and not run (a major change) versus a change that might have your build show a new violation (a minor change).

If we changed this logic about version numbers, then we would even need to increase the major version for bug fixes because fixing a bug would cause your build to throw new tslint violations.

**Comment by SimonSchick** [comment]
Guess we will keep a separate base ruleset then, thanks for clarifying.

**Comment by SimonSchick** [comment]
I'd suggest adding a note to https://github.com/Microsoft/tslint-microsoft-contrib#which-rules-should-i-turn-on that the default rule set should not be considered stable and may change with any minor/patch version.

Feel free to close this issue.

**Comment by HamletDRC** [comment]
done
