### ISSUE TITLE
Add detection for @bind decorators in react-this-binding

### ISSUE THREAD

**Issue by connor4312** [Microsoft/tslint-microsoft-contrib#392]
It's common practice to do something like the following:

```tsx
import { bind } from 'decko';

class Foo extends Component {
  public render() {
    return <button onclick={this.sayHi}>Greet</button>;
  }

  @bind
  public sayHi() {
    alert('hi');
  }
}
```

Unfortunately the `react-this-binding-issue` rule isn't aware of this and gets tripped up.

I propose adding an option like `{ "bindDecorators": ["bind"] }` which looks at decorator names and flags functions with those decorators as having been bound. It can have sensible defaults like `["bind", "Bind"]`.

**Comment by cyberhck** [comment]
is this being considered?

**Comment by JoshuaKGoldberg** [comment]
@cyberhck absolutely! Everything with the [`Status: Accepting PRs`](https://github.com/Microsoft/tslint-microsoft-contrib/labels/Status%3A%20Accepting%20PRs) label is open to being contributed. Feel free to tackle this if you have time! 😊

**Comment by cyberhck** [comment]
I would, but I don't even know how to go about this :smile:

**Comment by IllusionMH** [comment]
@cyberhck if you are still interested in implementation I can provide you with tips about possible implementation.

Otherwise I can take on this issue if there are no more volunteers.

**Comment by cyberhck** [comment]
Yes please, can you provide me some tips? Since this will be my first attempt, I don't know of helper methods, and I don't know how to detect if a function is bound or not.

**Comment by IllusionMH** [comment]
@cyberhck ok.
First - understanding of AST for TypeScript code would help. You can use https://astexplorer.net/ (need to pick TypeScript as parser in the header) or https://ts-ast-viewer.com/ to see what are relations between nodes (`ClassDeclaration`, `MethodDeclaration`, `Decorator` etc.)

Next - files related to rule: [rule source](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/src/reactThisBindingIssueRule.ts) and [tests](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/src/tests/ReactThisBindingIssueRuleTests.ts).

In rule source code you'll need to add options parser inside Walker constructor (you can check other rules for example) and in [`VisitClassDeclaration`](https://github.com/Microsoft/tslint-microsoft-contrib/blob/master/src/reactThisBindingIssueRule.ts#L60) instead of empty array of bound declarations you want to add list of methods that has decorator with identifier specified in options. I'd propose to move code from `AstUtils.getDeclaredMethodNames` to this method and process both `declaredMethods` and `boundListeners` in the single run, but it up to you.

Test are regular Mocha tests with helpers that allow to compare liter result with array of error objects. For your case you'll need to use `TestHelper.assertViolationsWithOptions` and pass configuration with list of decorator names that will bind methods.

**Comment by cyberhck** [comment]
@IllusionMH 
- how can I run a specific test?
- ~~node-inspector fails for some reason.~~ turns out, I've to downgrade node for this.
- ~~How can I know the decorator which we're using actually does a bind?~~ Is there a place where I define a schema to let user know that `decorators` is a array of string which is accepted for bind? (for the rule options)
- looks like I've to set experimental decorators to true on tsconfig.json, can you verify?

**Comment by cyberhck** [comment]
@IllusionMH 
looks like I've to set experimental decorators to true on tsconfig.json, can you verify?

**Comment by cyberhck** [comment]
I've enabled experimentalDecorators for test data. Will send a PR soonish.

**Comment by connor4312** [comment]
Great job @cyberhck!
