### ISSUE TITLE
What does "Interpolation will only work for template strings" mean ?

### ISSUE THREAD

**Issue by bertolo1988** [Microsoft/tslint-microsoft-contrib#396]
I got lint error which i do not comprehend. Can you help me?

**Code:**

```typescript
function buildServerOptions(environment: string = 'prod'): IServerOptions {
    const CONFIG_PATH: string = '../../config/';
    const defaultOptionsPath: string = '${CONFIG_PATH}default.json';
    const environmentOptionsPath: string = '${CONFIG_PATH}${environment}.json';
    const defaultOptions: IServerOptions = JSON.parse(fs.readFileSync(defaultOptionsPath, 'utf8'));
    const environmentOptions: IServerOptions = JSON.parse(fs.readFileSync(environmentOptionsPath, 'utf8'));
    return Object.assign({}, defaultOptions, environmentOptions);
}
```
**Error:** 

ERROR:...[13, 33]: Interpolation will only work for template strings.
ERROR:...[14, 37]: Interpolation will only work for template strings.
ERROR:...[14, 51]: Interpolation will only work for template strings.

**Comment by HamletDRC** [comment]
Hi @bertolo1988 
The contents of the string '${CONFIG_PATH}default.json' looks like a template string... however it is using the single quote mark instead of the ` mark. 
The value of defaultOptionsPath will contain `${CONFIG_PATH}default.json`
It looks like what you want to do is have it contain `../../config/default.json`

**Comment by bertolo1988** [comment]
Thanks alot @HamletDRC . I had no ideia!

**Comment by HamletDRC** [comment]
In this case, I think it actually did find an error!

**Comment by bertolo1988** [comment]
Yes it did.
