### ISSUE TITLE
new rule: use let, not var.

### ISSUE THREAD

**Issue by loicraux** [Microsoft/tslint-microsoft-contrib#78]
I know this one is a matter for debate, but in my opinion, there is reason to use `var` in TypeScript/ES6 code since we now have `let`.

See http://programmers.stackexchange.com/a/274352 and Crockford's point about `let` : http://youtu.be/vJKDh4UEXhw?t=28m4s

Corresponding eslint rule : http://eslint.org/docs/rules/no-var

**Comment by loicraux** [comment]
Closing issue since rule exists in tslint

**Comment by joshbw** [comment]
Do you mean to say “there is no reason to use var in TypeScript/ES6 code since we now have let”

If so, I generally agree, though I don’t think var is harmful if used in something where function scope is clearly intended (i.e. at the top of a function rather than within a block).  I’d consider declaring a var within a block to be a flaw, as either it should be declared outside of a block or let should be used instead.

**Comment by HamletDRC** [comment]
Hi @joshbw 
I think the tslint rule "no-var-keyword" does exactly this. The tslint docs say: 

    no-var-keyword disallows usage of the var keyword, use let or const instead

Sorry if the comments in the issue were not 100% clear. Loïc and I sit across from each other at work, so it's pretty easy to have a quick discussion and write some cryptic comments in the issues here :)

**Comment by joshbw** [comment]
Awesome, thanks Hamlet

Sent from my Windows Phone
________________________________
