### ISSUE TITLE
react-unused-props-and-state malfunctioning

### ISSUE THREAD

**Issue by pierre-aurele-martin** [Microsoft/tslint-microsoft-contrib#811]
### Bug Report

-   **`tslint-microsoft-contrib` version**: 6.0.0
-   **TSLint version**: 5.12.1
-   **TypeScript version**: 3.2.2
-   **Running TSLint via**: CLI && Code

#### TypeScript code being linted

```tsx
import { React } from '../../../../commons';

interface ITestProps {
  nope: boolean;
}

export class Test extends React.PureComponent<ITestProps, any> {

  constructor(props) {
    super(props);
  }

  render() {
    const blah = this.props;
    return <div></div>;
  }
}
```

with `tslint.json` configuration:

```json
{
    "extends": ["tslint:recommended"],
    "rulesDirectory": ["node_modules/tslint-microsoft-contrib"],
    "rules": {
        "react-unused-props-and-state": [true,{"props-interface-regex": "Props$", "state-interface-regex": "State$"}],
    }
}
```

#### Actual behavior

By just using this.props in render(), I'm disabling the alert for UnUsed React Props.

#### Expected behavior

The linter should tell me that property **nope** defined in interface is not used because at no point I'm using this.props.nope...

**Comment by IllusionMH** [comment]
Looks like this is design limitation.
In your example whole `props` object is used (to assign it to new variable) and in general case it is impossible to tell whether it was used at all.

Rule checks `this.props.someProp` usages, removes them from list of unused, and then highlight any prop that is still in list, but when whole `this.props` or `this.state`  is used then list is cleared because all properties was used to pass assing them all to new variable, pass to callback etc.

**Comment by pierre-aurele-martin** [comment]
To note that it's the samething for state as long as your writing : 

`this.state = {...}`

in your constructor, every states are considered as used.

Thank you for the quick answer,

**Comment by IllusionMH** [comment]
> To note that it's the samething for state as long as your writing :
> `this.state = {...}`

Thanks for pointing this out.

While `const a = this.props` and `const b = this.state` at this point should mark all props as used.
I think that `this.state = {...}` should be an exception.

I'll check logic and create separate issue if this one shouldn't mark all properties(keys) as used.
