### ISSUE TITLE
react-no-tsx-without-jsx-elements

### ISSUE THREAD

**Issue by joeyj-msft** [microsoft/tslint-microsoft-contrib#874]
### Rule Suggestion

**Is your rule for a general problem or is it specific to your development style?**
General issue with engineers using .tsx extension by copying convention when .tsx is reserved for React.

**What does your suggested rule do?**
Enforces that .tsx files should contain JSX Elements.

**Additional context**
I have a working tslint rule and would be happy to contribute with tests.

**Comment by JoshuaKGoldberg** [comment]
@joeyj-msft this seems like a valid rule & good idea, but I would actually prefer the opposite: banning `.ts` files in favor of always preferring `.tsx`. It's annoying having to rename files when they start or stop containing JSX elements.

Accepting PRs for a rule named something like `tsx-file-extension` or `tsx-without-jsx` that accepts an option for either preference.

**Comment by joeyj-msft** [comment]
I think tsx-without-jsx follows YAGNE fairly cleanly. I'll see about getting a PR

**Comment by JoshuaKGoldberg** [comment]
@joeyj-msft on the other hand, the presence of `.ts` files could also be interpreted as a violation of You Ain't Gonna Need It. What is the benefit of splitting view files from other files by extension? Some would say it's an unnecessary overhead that doesn't justify the conceptual cost of making it more difficult to manipulate files.
* What happens if you want to include JSX syntax in a store file?
* It's harder to copy and paste code when some previously acceptable syntax isn't allowed I'm the target file
* Explaining the extensions' difference and historical context is a slight increase in the learning curve for developers new to Typescript

Speaking even more generally: it is not tslint-microsoft-contrib's place to take a hard stand on a code style preference where the benefits of one option don't clearly the other sides. Unless there is community consensus around extensions _and_ there is shown to be a non-trivial negative impact of choosing one style over the other, it would be disruptive to our users to arbitrarily pick one over the other.

**Comment by joeyj-msft** [comment]
Since there is controversy in this issue. I'm retracting my PR.

**Comment by joeyj-msft** [comment]
YAGNI means you are adding support for something you don't need yet. Using .jsx/.tsx violates this principle. This is likely not the best repo to add a rule like this. :)
