### ISSUE TITLE
HTML a11y rules

### ISSUE THREAD

**Issue by fabioemoutinho** [microsoft/tslint-microsoft-contrib#892]
### Feature request

**Is your feature request that we implement a new rule?**
No.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
a11y rules should support .html files also (is it possible?)

**Describe alternatives you've considered**
new rules?

**Comment by IllusionMH** [comment]
@fabioemoutinho thank you for interest in the project, however it is something that is outside of this repo scope.

This repo only provides set of check for parsed files and relies on TSLint which in turn uses TS. TS doesn't support support for HTML files.

If you want to validate regular HTML files without any JSX in JS/TS you should check https://webhint.io/ and its accessibility checks https://webhint.io/docs/user-guide/hints/accessibility/

If you have files with `.html` extension with JSX syntax inside them - you need to do something similar to what https://github.com/prograhammer/vscode-tslint-vue does, however I'm not familiar with their approach.

Since this issue doesn't have any actionable items for this repo I'll close it.

**Comment by fabioemoutinho** [comment]
if there are people struggling to find lint rules for a11y in angular, I just found out that there are rules in codelyzer, check their repo
